#! /bin/bash
a=$(cat /etc/os-release | grep "ID_LIKE" | grep -m1 -o "\".*")
d="debian"
r="\"rhel fedora\""

if [ "$a" = "$d" ]; then

echo "enter ip"
read ip
echo "network:">/etc/netplan/00-installer-config.yaml
echo "  version: 2">>/etc/netplan/00-installer-config.yaml
echo "  renderer: networkd">>/etc/netplan/00-installer-config.yaml
echo "  ethernets:">>/etc/netplan/00-installer-config.yaml
echo "    enp0s3:">>/etc/netplan/00-installer-config.yaml
echo "      dhcp4: no">>/etc/netplan/00-installer-config.yaml
echo "      dhcp6: no">>/etc/netplan/00-installer-config.yaml
echo "      addresses: [$ip/24]">>/etc/netplan/00-installer-config.yaml
echo "      gateway4: 192.168.0.1">>/etc/netplan/00-installer-config.yaml
echo "      nameservers:">>/etc/netplan/00-installer-config.yaml
echo "        addresses: [8.8.8.8,8.8.4.4]">>/etc/netplan/00-installer-config.yaml
sudo netplan apply
exit 1

elif [ "$a" = "$r" ]; then

uuid=$(cat /etc/sysconfig/network-scripts/ifcfg-en* | grep "UUID")
name=$(cat /etc/sysconfig/network-scripts/ifcfg-en* | grep "NAME")
device=$(cat /etc/sysconfig/network-scripts/ifcfg-en* | grep "DEVICE")
read -r -p "IPADDR=" ip
read -r -p "GATEWAY=" ip_gateway
read -r -p "NETMASK=" ip_netmask
read -r -p "DNS1=" ip_dns
echo "TYPE=\"Ethernet\""> /etc/sysconfig/network-scripts/ifcfg-en*
echo "PROXY_METHOD=\"none\"">> /etc/sysconfig/network-scripts/ifcfg-en*
echo "BROWSER_ONLY=\"no\"">> /etc/sysconfig/network-scripts/ifcfg-en*
echo "BOOTPROTO=\"static\"">> /etc/sysconfig/network-scripts/ifcfg-en*
echo "DEFROUTE=\"yes\"">> /etc/sysconfig/network-scripts/ifcfg-en*
echo "IPV4_FAILURE_FATAL=\"no\"">> /etc/sysconfig/network-scripts/ifcfg-en*
echo "NAME=\"$name\"">> /etc/sysconfig/network-scripts/ifcfg-en*
echo "UUID=\"$uuid\"">> /etc/sysconfig/network-scripts/ifcfg-en*
echo $name >> /etc/sysconfig/network-scripts/ifcfg-en*
echo "ONBOOT=\"yes\"">> /etc/sysconfig/network-scripts/ifcfg-en*
echo "IPADDR=\"$ip\"" >> /etc/sysconfig/network-scripts/ifcfg-en*
echo "NETMASK=\"$ip_netmask\"" >> /etc/sysconfig/network-scripts/ifcfg-en*
echo "GATEWAY=\"$ip_gateway\"" >> /etc/sysconfig/network-scripts/ifcfg-en*
echo "DNS1=\"$ip_dns\"" >> /etc/sysconfig/network-scripts/ifcfg-en*
systemctl restart network

fi
